In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("weather_data.csv")

In [3]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        7.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [4]:
df.isnull()

     day  temperature  windspeed  event
0  False        False      False  False
1  False         True      False  False
2  False        False       True  False
3  False         True      False   True
4  False        False       True  False
5  False        False      False  False
6  False         True       True   True
7  False        False      False  False
8  False        False      False  False

In [5]:
df.isnull().sum()

day            0
temperature    3
windspeed      3
event          2
dtype: int64

In [6]:
df[df['temperature'].isnull()]

        day  temperature  windspeed  event
1  1/4/2017          NaN        7.0  Sunny
3  1/6/2017          NaN        7.0    NaN
6  1/9/2017          NaN        NaN    NaN

In [7]:
df.dropna()

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
5   1/8/2017         31.0        2.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [8]:
df_clean=df.dropna(how='all')

In [9]:
df_clean

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        7.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [10]:
df_clean = df.dropna(subset=['temperature'])
df_clean

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
2   1/5/2017         28.0        NaN    Snow
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017         31.0        2.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [11]:
before_shape = df.shape
print("before shape",before_shape)

df_clean=df.dropna()
after_shape=df_clean.shape
print("after shape",after_shape)

before shape (9, 4)
after shape (4, 4)

In [12]:
df.fillna(0)

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          0.0        7.0   Sunny
2   1/5/2017         28.0        0.0    Snow
3   1/6/2017          0.0        7.0       0
4   1/7/2017         32.0        0.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017          0.0        0.0       0
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [13]:
import numpy as np

In [14]:
np.mean(df['temperature'])

np.float64(32.833333333333336)

In [15]:
df['temperature'].mean()

np.float64(32.833333333333336)

In [16]:
new_df = df.fillna(method="bfill")
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_18616\200175317.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method="bfill")

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         28.0        7.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         32.0        7.0    Rain
4   1/7/2017         32.0        2.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017         34.0        8.0  Cloudy
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [17]:
new_df = df.fillna(method="ffill")
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_18616\2534372125.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method="ffill")

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        7.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017         31.0        2.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [18]:
df['day'] = pd.to_datetime(df['day'])
df = df.set_index('day')

In [19]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [20]:
df=df.asfreq('D')

In [21]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [22]:
mean_temp = np.nanmean(df['temperature'])

In [23]:
df['temperature'] = df['temperature'].fillna(mean_temp)
df

            temperature  windspeed   event
day
2017-01-01    32.000000        6.0    Rain
2017-01-02    32.833333        NaN     NaN
2017-01-03    32.833333        NaN     NaN
2017-01-04    32.833333        7.0   Sunny
2017-01-05    28.000000        NaN    Snow
2017-01-06    32.833333        7.0     NaN
2017-01-07    32.000000        NaN    Rain
2017-01-08    31.000000        2.0   Sunny
2017-01-09    32.833333        NaN     NaN
2017-01-10    34.000000        8.0  Cloudy
2017-01-11    40.000000       12.0   Sunny

In [24]:
df['temperature']=df['temperature'].replace(0,mean_temp)

In [25]:
df

            temperature  windspeed   event
day
2017-01-01    32.000000        6.0    Rain
2017-01-02    32.833333        NaN     NaN
2017-01-03    32.833333        NaN     NaN
2017-01-04    32.833333        7.0   Sunny
2017-01-05    28.000000        NaN    Snow
2017-01-06    32.833333        7.0     NaN
2017-01-07    32.000000        NaN    Rain
2017-01-08    31.000000        2.0   Sunny
2017-01-09    32.833333        NaN     NaN
2017-01-10    34.000000        8.0  Cloudy
2017-01-11    40.000000       12.0   Sunny

In [26]:
new_df=df.groupby("temperature")

In [27]:
new_df

In [28]:
new_df=df.groupby("event")

In [29]:
new_df

In [30]:
stats = df.groupby('event')['temperature'].agg(
    mean='mean',
    count='count',
    max='max',
    min='min',
    std='std'
)

In [31]:
stats

             mean  count   max   min       std
event
Cloudy  34.000000      1  34.0  34.0       NaN
Rain    32.000000      2  32.0  32.0  0.000000
Snow    28.000000      1  28.0  28.0       NaN
Sunny   34.611111      3  40.0  31.0  4.756088

In [32]:
df_clean.to_csv('cleaned_weather.csv', index=False)

# <font color="blue">Assignment </color>

In [33]:
sales_df = pd.DataFrame({
    'Order_ID': [101, 102, 103, 104],
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Laptop'],
    'Quantity': [2, 5, 3, 1],
    'Price': [50000, 20000, 15000, 50000]
})

In [34]:
sales_df

   Order_ID Product  Quantity  Price
0       101  Laptop         2  50000
1       102  Mobile         5  20000
2       103  Tablet         3  15000
3       104  Laptop         1  50000

In [35]:
marks_df = pd.DataFrame({
    'Roll_No': [1, 2, 3, 4],
    'Name': ['Prince', 'a', 'b', 'c'],
    'Maths': [85, 78, 92, 67],
    'Physics': [88, 74, 90, 70],
    'Chemistry': [80, 82, 85, 75]
})
marks_df

   Roll_No    Name  Maths  Physics  Chemistry
0        1  Prince     85       88         80
1        2       a     78       74         82
2        3       b     92       90         85
3        4       c     67       70         75

In [36]:
print("weathere : ",df.isnull().sum())
print("sales : ",sales_df.isnull().sum())
print("marrks : ",marks_df.isnull().sum())

weathere :  temperature    0
windspeed      5
event          4
dtype: int64
sales :  Order_ID    0
Product     0
Quantity    0
Price       0
dtype: int64
marrks :  Roll_No      0
Name         0
Maths        0
Physics      0
Chemistry    0
dtype: int64

In [37]:
mean_t=np.mean(df['temperature'])

In [38]:
df['temperature']=df['temperature'].fillna(mean_t)

In [39]:
df

            temperature  windspeed   event
day
2017-01-01    32.000000        6.0    Rain
2017-01-02    32.833333        NaN     NaN
2017-01-03    32.833333        NaN     NaN
2017-01-04    32.833333        7.0   Sunny
2017-01-05    28.000000        NaN    Snow
2017-01-06    32.833333        7.0     NaN
2017-01-07    32.000000        NaN    Rain
2017-01-08    31.000000        2.0   Sunny
2017-01-09    32.833333        NaN     NaN
2017-01-10    34.000000        8.0  Cloudy
2017-01-11    40.000000       12.0   Sunny

In [40]:
mean_w=np.mean(df['windspeed'])

In [41]:
df['windspeed']=df['windspeed'].fillna(mean_w)

In [42]:
df

            temperature  windspeed   event
day
2017-01-01    32.000000        6.0    Rain
2017-01-02    32.833333        7.0     NaN
2017-01-03    32.833333        7.0     NaN
2017-01-04    32.833333        7.0   Sunny
2017-01-05    28.000000        7.0    Snow
2017-01-06    32.833333        7.0     NaN
2017-01-07    32.000000        7.0    Rain
2017-01-08    31.000000        2.0   Sunny
2017-01-09    32.833333        7.0     NaN
2017-01-10    34.000000        8.0  Cloudy
2017-01-11    40.000000       12.0   Sunny

In [62]:
df=pd.DataFrame({
    'Student_ID': [1, 2, 3, 4, 5],
    'Name': ['A', 'B', 'C', 'E', 'D'],
    'Gender': ['M', 'Female', 'male', 'F', 'Male'],
    'Marks': [85, np.nan, 78, 90, None],
    'City': ['Delhi', 'Mumbai', 'Mumbai', 'Delhi', 'mumbai']
})

In [63]:
print("before : ",df)

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
df['Gender'] = df['Gender'].replace(
    {'M':'Male', 'male':'Male', 'F':'Female'}
)
print("after : ",df)

before :     Student_ID Name  Gender  Marks    City
0           1    A       M   85.0   Delhi
1           2    B  Female    NaN  Mumbai
2           3    C    male   78.0  Mumbai
3           4    E       F   90.0   Delhi
4           5    D    Male    NaN  mumbai
after :     Student_ID Name  Gender      Marks    City
0           1    A    Male  85.000000   Delhi
1           2    B  Female  84.333333  Mumbai
2           3    C    Male  78.000000  Mumbai
3           4    E  Female  90.000000   Delhi
4           5    D    Male  84.333333  mumbai

In [65]:
g=df.groupby('City')
g

In [70]:
agg=df.groupby('City')['Marks'].agg(
        mean='mean',
        max='max',
        count='count'
)
agg

             mean        max  count
City
Delhi   87.500000  90.000000      2
Mumbai  81.166667  84.333333      2
mumbai  84.333333  84.333333      1

In [72]:
df.to_csv('cleaned_student_detail.csv')

In [73]:
df

   Student_ID Name  Gender      Marks    City
0           1    A    Male  85.000000   Delhi
1           2    B  Female  84.333333  Mumbai
2           3    C    Male  78.000000  Mumbai
3           4    E  Female  90.000000   Delhi
4           5    D    Male  84.333333  mumbai