In [1]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\patel\anaconda3\lib\site-packages (2.3.5)

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\patel\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\patel\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\patel\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\patel\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\patel\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\patel\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import numpy as np

df=pd.read_csv("weadher_data.csv",parse_dates=['day'])
df

FileNotFoundError: [Errno 2] No such file or directory: 'weadher_data.csv'

In [4]:
import pandas as pd
import numpy as np

df=pd.read_csv("weather_data.csv",parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [5]:
new_df=df.set_index('day')
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [7]:
df.set_index('day',inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [8]:
new_df=df.fillna(0)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        7.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [9]:
new_df = df.fillna({
    'temperature' : '0',
    'windspeed' : '1',
    'Event' : 'No Event',
})
new_df

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04           0       7.0   Sunny
2017-01-05        28.0         1    Snow
2017-01-06           0       7.0     NaN
2017-01-07        32.0         1    Rain
2017-01-08        31.0       2.0   Sunny
2017-01-09           0         1     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

In [10]:
new_df = df.fillna(method="ffill")
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_19700\2534372125.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method="ffill")

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         31.0        2.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [11]:
new_df = df.fillna(method="'bfill")
neww_df

ValueError: Invalid fill method. Expecting pad (ffill) or backfill (bfill). Got 'bfill

In [12]:
new_df=df.bfill()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        2.0    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [13]:
new_df=df.ffill()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         31.0        2.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [15]:
new_df = df.fillna(method="ffill",axis="columns")
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_19700\4174896266.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method="ffill",axis="columns")
C:\Users\patel\AppData\Local\Temp\ipykernel_19700\4174896266.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = df.fillna(method="ffill",axis="columns")

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         NaN       7.0   Sunny
2017-01-05        28.0      28.0    Snow
2017-01-06         NaN       7.0     7.0
2017-01-07        32.0      32.0    Rain
2017-01-08        31.0       2.0   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

In [16]:
new_df = df.fillna(method="ffill",limit=1)
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_19700\2057544078.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method="ffill",limit=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         31.0        2.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [17]:
new_df = df.interpolate()
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_19700\812076388.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         30.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         30.0        7.0     NaN
2017-01-07         32.0        4.5    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         32.5        5.0     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [18]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [23]:
new_df = df.interpolate(method="time") 
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_19700\2760325171.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method="time")

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         29.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         30.0        7.0     NaN
2017-01-07         32.0        4.5    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         32.5        5.0     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [22]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [24]:
new_df = df.interpolate(method="time") 
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_19700\2760325171.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method="time")

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         29.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         30.0        7.0     NaN
2017-01-07         32.0        4.5    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         32.5        5.0     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [25]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [26]:
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         29.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         30.0        7.0     NaN
2017-01-07         32.0        4.5    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         32.5        5.0     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [27]:
new_df = df
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [28]:
new_df=df.interpolate()
new_df

C:\Users\patel\AppData\Local\Temp\ipykernel_19700\1725489846.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df=df.interpolate()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         30.0        7.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         30.0        7.0     NaN
2017-01-07         32.0        4.5    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09         32.5        5.0     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [29]:
new_df = df
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [30]:
new_df = df
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [31]:
new_df = df.dropna(how='all')
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [32]:
new_df = df
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [33]:
new_df = df.dropna(thresh=1) #Only Keep Rows with Minimum Number of non-NaN Values
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [34]:
new_df = df
new_df = df.dropna(how='all')
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        7.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08         31.0        2.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny