In [1]:
import numpy as np
import pandas as pd

In [3]:

i_arr=np.array([1,2,3,4,5])
f_arr=np.array([1.1,2.2,3.3,4.4,5.5])
m_arr=np.array(([1,2.2,3,4.4,5]),dtype=object)

print("int array",i_arr)
print("float array",f_arr)
print("mixed array",m_arr)

int array [1 2 3 4 5]
float array [1.1 2.2 3.3 4.4 5.5]
mixed array [1 2.2 3 4.4 5]

In [7]:
print("max",np.max(i_arr))
print("min",np.min(i_arr))
print("division",i_arr/2)

max 5
min 1
division [0.5 1.  1.5 2.  2.5]

In [8]:
print("mean",np.mean(i_arr))

mean 3.0

In [10]:
scores_np = np.array([1,2,3,4])

days_index = ['Mon', 'Tue', 'Wed', 'Thu']

scores_series = pd.Series(scores_np, index=days_index)

print("--- Scores by Day ---",scores_series)

--- Scores by Day --- Mon    1
Tue    2
Wed    3
Thu    4
dtype: int64

In [14]:
s=pd.DataFrame(scores_series)
print("result:",s[0],s[0:4])

result: Mon    1
Tue    2
Wed    3
Thu    4
Name: 0, dtype: int64      0
Mon  1
Tue  2
Wed  3
Thu  4

In [15]:
s.head()

     0
Mon  1
Tue  2
Wed  3
Thu  4

In [16]:
s.tail()

     0
Mon  1
Tue  2
Wed  3
Thu  4

In [18]:
s.describe()

              0
count  4.000000
mean   2.500000
std    1.290994
min    1.000000
25%    1.750000
50%    2.500000
75%    3.250000
max    4.000000

In [23]:
df=pd.read_csv("weather_data.csv")
df

          day  temperature  windspeed  event
0  01-01-2019           37          6   Rain
1  02-01-2019           35          7  Sunny
2  03-01-2019           38          2   Snow
3  04-01-2019           34          7   Snow
4  05-01-2019           32          4   Rain
5  06-01-2019           31          2  Sunny

In [24]:
df.head()

          day  temperature  windspeed  event
0  01-01-2019           37          6   Rain
1  02-01-2019           35          7  Sunny
2  03-01-2019           38          2   Snow
3  04-01-2019           34          7   Snow
4  05-01-2019           32          4   Rain

In [25]:
df.tail()

          day  temperature  windspeed  event
1  02-01-2019           35          7  Sunny
2  03-01-2019           38          2   Snow
3  04-01-2019           34          7   Snow
4  05-01-2019           32          4   Rain
5  06-01-2019           31          2  Sunny

In [26]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     34.500000   4.666667
std       2.738613   2.338090
min      31.000000   2.000000
25%      32.500000   2.500000
50%      34.500000   5.000000
75%      36.500000   6.750000
max      38.000000   7.000000

In [27]:
df["temperature"]

0    37
1    35
2    38
3    34
4    32
5    31
Name: temperature, dtype: int64

In [28]:
df[["temperature", "windspeed"]]

   temperature  windspeed
0           37          6
1           35          7
2           38          2
3           34          7
4           32          4
5           31          2

In [29]:
df.loc[2]       
df.loc[2:4]

          day  temperature  windspeed event
2  03-01-2019           38          2  Snow
3  04-01-2019           34          7  Snow
4  05-01-2019           32          4  Rain

In [30]:
df.iloc[0:3, 1:3]

   temperature  windspeed
0           37          6
1           35          7
2           38          2

In [31]:
df[df["temperature"] > 35]

          day  temperature  windspeed event
0  01-01-2019           37          6  Rain
2  03-01-2019           38          2  Snow

In [32]:
df[df["event"] == "Sunny"]

          day  temperature  windspeed  event
1  02-01-2019           35          7  Sunny
5  06-01-2019           31          2  Sunny

In [33]:
df["temp_F"] = (df["temperature"] * 9/5) + 32

In [34]:
df["temp_wind_index"] = df["temperature"] / df["windspeed"]

In [35]:
df.to_csv("updated_weather.csv", index=False)

In [38]:
df

          day  temperature  windspeed  event  temp_F  temp_wind_index
0  01-01-2019           37          6   Rain    98.6         6.166667
1  02-01-2019           35          7  Sunny    95.0         5.000000
2  03-01-2019           38          2   Snow   100.4        19.000000
3  04-01-2019           34          7   Snow    93.2         4.857143
4  05-01-2019           32          4   Rain    89.6         8.000000
5  06-01-2019           31          2  Sunny    87.8        15.500000

# <font color="blue">Assignment </color>

In [39]:
daily_sales=["mon","tue","wen","thu","fri","sat","sun"];
day=[1,2,3,4,5,6,7]
s=pd.Series(day,index=daily_sales)

In [40]:
s

mon    1
tue    2
wen    3
thu    4
fri    5
sat    6
sun    7
dtype: int64

In [41]:
indata={
   'roll_no' : [1,2,3,4,5],
    'name' : ["prince","a","b","c","d"],
    'chemestry': [95,84,86,79,91],
    'physics':[92,86,75,68,83],
    'maths':[78,85,95,84,76],
}
df=pd.DataFrame(indata)
df

   roll_no    name  chemestry  physics  maths
0        1  prince         95       92     78
1        2       a         84       86     85
2        3       b         86       75     95
3        4       c         79       68     84
4        5       d         91       83     76

In [42]:
df.set_index(['roll_no'])

           name  chemestry  physics  maths
roll_no
1        prince         95       92     78
2             a         84       86     85
3             b         86       75     95
4             c         79       68     84
5             d         91       83     76

In [43]:
print("using pandas",df[['chemestry', 'physics', 'maths']].describe())

using pandas        chemestry    physics      maths
count   5.000000   5.000000   5.000000
mean   87.000000  80.800000  83.600000
std     6.204837   9.418068   7.436397
min    79.000000  68.000000  76.000000
25%    84.000000  75.000000  78.000000
50%    86.000000  83.000000  84.000000
75%    91.000000  86.000000  85.000000
max    95.000000  92.000000  95.000000

In [44]:
marks= [95,84,86,79,91]
print("------using numpy------")
print("Max Marks", np.max(marks))
print("Min Marks",np.min(marks))
print("Mean Marks",np.mean(marks))
print("Std Dev",np.std(marks))

------using numpy------
Max Marks 95
Min Marks 79
Mean Marks 87.0
Std Dev 5.549774770204643

In [45]:
marks_cols=["chemestry","physics","maths"]
df['Percentage'] = (df[marks_cols].sum(axis=1).to_numpy() / 300) * 100
df

   roll_no    name  chemestry  physics  maths  Percentage
0        1  prince         95       92     78   88.333333
1        2       a         84       86     85   85.000000
2        3       b         86       75     95   85.333333
3        4       c         79       68     84   77.000000
4        5       d         91       83     76   83.333333

In [46]:
numeric_df = df.select_dtypes(include=np.number)

data = numeric_df.values

mean_values = np.mean(data, axis=0)
median_values = np.median(data, axis=0)

print("\nColumn-wise Mean:", mean_values)
print("Column-wise Median:", median_values)

row_totals = np.sum(data[:, :3], axis=1) 
max_index = np.argmax(row_totals)

print("\nStudent with highest total marks:")
print(df.iloc[max_index])

Column-wise Mean: [ 3.  87.  80.8 83.6 83.8]
Column-wise Median: [ 3. 86. 83. 84. 85.]

Student with highest total marks:
roll_no               1
name             prince
chemestry            95
physics              92
maths                78
Percentage    88.333333
Name: 0, dtype: object

In [47]:
rows, columns = df.shape

In [48]:
df.shape

(5, 6)