In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
daily_sales=["mon","tue","wen","thu","fri","sat","sun"];
day=[1,2,3,4,5,6,7]
s=pd.Series(day,index=daily_sales)

In [5]:
s

mon    1
tue    2
wen    3
thu    4
fri    5
sat    6
sun    7
dtype: int64

In [17]:
indata={
   'roll_no' : [1,2,3,4,5],
    'name' : ["prince","a","b","c","d"],
    'chemestry': [95,84,86,79,91],
    'physics':[92,86,75,68,83],
    'maths':[78,85,95,84,76],
}
df=pd.DataFrame(indata)
df

   roll_no    name  chemestry  physics  maths
0        1  prince         95       92     78
1        2       a         84       86     85
2        3       b         86       75     95
3        4       c         79       68     84
4        5       d         91       83     76

In [18]:
df.set_index(['roll_no'], inplace=True)

In [19]:
df

           name  chemestry  physics  maths
roll_no
1        prince         95       92     78
2             a         84       86     85
3             b         86       75     95
4             c         79       68     84
5             d         91       83     76

In [20]:
df.to_csv("indata.csv")

In [23]:
print("using pandas",df[['chemestry', 'physics', 'maths']].describe())

using pandas        chemestry    physics      maths
count   5.000000   5.000000   5.000000
mean   87.000000  80.800000  83.600000
std     6.204837   9.418068   7.436397
min    79.000000  68.000000  76.000000
25%    84.000000  75.000000  78.000000
50%    86.000000  83.000000  84.000000
75%    91.000000  86.000000  85.000000
max    95.000000  92.000000  95.000000

In [15]:
marks= [95,84,86,79,91]
print("------using numpy------")
print("Max Marks", np.max(marks))
print("Min Marks",np.min(marks))
print("Mean Marks",np.mean(marks))
print("Std Dev",np.std(marks))

------using numpy------
Max Marks 95
Min Marks 79
Mean Marks 87.0
Std Dev 5.549774770204643

In [25]:
marks_cols=["chemestry","physics","maths"]
df['Percentage'] = (df[marks_cols].sum(axis=1).to_numpy() / 300) * 100
df

           name  chemestry  physics  maths  Percentage
roll_no
1        prince         95       92     78   88.333333
2             a         84       86     85   85.000000
3             b         86       75     95   85.333333
4             c         79       68     84   77.000000
5             d         91       83     76   83.333333

In [27]:

numeric_df = df.select_dtypes(include=np.number)

data = numeric_df.values

mean_values = np.mean(data, axis=0)
median_values = np.median(data, axis=0)

print("\nColumn-wise Mean:", mean_values)
print("Column-wise Median:", median_values)

row_totals = np.sum(data[:, :3], axis=1) 
max_index = np.argmax(row_totals)

print("\nStudent with highest total marks:")
print(df.iloc[max_index])

Column-wise Mean: [87.  80.8 83.6 83.8]
Column-wise Median: [86. 83. 84. 85.]

Student with highest total marks:
name             prince
chemestry            95
physics              92
maths                78
Percentage    88.333333
Name: 1, dtype: object

In [28]:

df.to_csv("cleaned_student_data.csv")

print("Data saved successfully!")

Data saved successfully!

In [29]:
rows, columns = df.shape

In [31]:
df.shape

(5, 5)

In [32]:
df

           name  chemestry  physics  maths  Percentage
roll_no
1        prince         95       92     78   88.333333
2             a         84       86     85   85.000000
3             b         86       75     95   85.333333
4             c         79       68     84   77.000000
5             d         91       83     76   83.333333