In [1]:
import pandas as pd

In [2]:
jan_sales =pd.DataFrame({
    "Product": ["Pen", "Pencil", "Notebook"],
    "Quantity": [120, 200, 75],
    "Revenue": [600, 400, 1500]
})

jan_sales

    Product  Quantity  Revenue
0       Pen       120      600
1    Pencil       200      400
2  Notebook        75     1500

In [3]:
Feb_sales = pd.DataFrame([
    ["Pen", 150, 750],
    ["Pencil", 180, 360],
    ["Notebook", 90, 1800]
]
)
Feb_sales

          0    1     2
0       Pen  150   750
1    Pencil  180   360
2  Notebook   90  1800

In [4]:
df=pd.concat([jan_sales,Feb_sales])
df

    Product  Quantity  Revenue         0      1       2
0       Pen     120.0    600.0       NaN    NaN     NaN
1    Pencil     200.0    400.0       NaN    NaN     NaN
2  Notebook      75.0   1500.0       NaN    NaN     NaN
0       NaN       NaN      NaN       Pen  150.0   750.0
1       NaN       NaN      NaN    Pencil  180.0   360.0
2       NaN       NaN      NaN  Notebook   90.0  1800.0

In [5]:
df_hor=pd.concat([jan_sales,Feb_sales],axis=1)
df_hor

    Product  Quantity  Revenue         0    1     2
0       Pen       120      600       Pen  150   750
1    Pencil       200      400    Pencil  180   360
2  Notebook        75     1500  Notebook   90  1800

In [6]:
df=pd.concat([jan_sales,Feb_sales],ignore_index=True)
df

    Product  Quantity  Revenue         0      1       2
0       Pen     120.0    600.0       NaN    NaN     NaN
1    Pencil     200.0    400.0       NaN    NaN     NaN
2  Notebook      75.0   1500.0       NaN    NaN     NaN
3       NaN       NaN      NaN       Pen  150.0   750.0
4       NaN       NaN      NaN    Pencil  180.0   360.0
5       NaN       NaN      NaN  Notebook   90.0  1800.0

In [7]:
df1=pd.DataFrame({
    "name":["prince","a","b","c"],
    "marks":[95,78,85,75],
    "course":["ce","cse","it","ce"],
})

df1

     name  marks course
0  prince     95     ce
1       a     78    cse
2       b     85     it
3       c     75     ce

In [8]:
df2=pd.DataFrame({
     "name":["prince","a","b","c"],
    "marks":[85,98,65,85],
    "course":["cse","ce","it","it"],
})

In [9]:
df2

     name  marks course
0  prince     85    cse
1       a     98     ce
2       b     65     it
3       c     85     it

In [10]:
df=pd.merge(df1,df2,on="name",how="inner")

In [11]:
df

     name  marks_x course_x  marks_y course_y
0  prince       95       ce       85      cse
1       a       78      cse       98       ce
2       b       85       it       65       it
3       c       75       ce       85       it

In [12]:
df=pd.merge(df1,df2,on="name",how="outer")
df

     name  marks_x course_x  marks_y course_y
0       a       78      cse       98       ce
1       b       85       it       65       it
2       c       75       ce       85       it
3  prince       95       ce       85      cse

In [13]:
df=pd.merge(df1,df2,on="name",how="left")
df

     name  marks_x course_x  marks_y course_y
0  prince       95       ce       85      cse
1       a       78      cse       98       ce
2       b       85       it       65       it
3       c       75       ce       85       it

In [14]:
df=pd.merge(df1,df2,on="name",how="right")
df

     name  marks_x course_x  marks_y course_y
0  prince       95       ce       85      cse
1       a       78      cse       98       ce
2       b       85       it       65       it
3       c       75       ce       85       it

In [15]:
df.to_csv("students.csv")

In [16]:
df=pd.merge(df1,df2,on="name",how="outer",suffixes=('_left','_right'))
df

     name  marks_left course_left  marks_right course_right
0       a          78         cse           98           ce
1       b          85          it           65           it
2       c          75          ce           85           it
3  prince          95          ce           85          cse

In [17]:
df=pd.read_csv("weather2.csv")
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [18]:
df.pivot_table(index="city",columns="date")
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [19]:
df.pivot_table(index="city",columns="date")

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

In [20]:
df.pivot_table(index="city",columns="date",aggfunc="mean")

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

In [21]:
df.pivot_table(index="city",columns="date",aggfunc="max")

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai         83       85          78       82
new york       56       62          65       72

In [22]:
df = pd.pivot_table(
    df,
    index="city",
    columns="date",
    values="humidity"
)

In [23]:
df

date      5/1/2017  5/2/2017
city
mumbai        81.5      55.5
new york      55.0      61.0

In [24]:
long_df = df.reset_index().melt(
    id_vars="city",
    value_vars=["5/1/2017", "5/2/2017"],
    var_name="date",
    value_name="humidity"
)
long_df

       city      date  humidity
0    mumbai  5/1/2017      81.5
1  new york  5/1/2017      55.0
2    mumbai  5/2/2017      55.5
3  new york  5/2/2017      61.0

In [25]:
stacked = df.stack()

In [26]:
stacked

city      date
mumbai    5/1/2017    81.5
          5/2/2017    55.5
new york  5/1/2017    55.0
          5/2/2017    61.0
dtype: float64

In [27]:
unstacked = stacked.unstack()
unstacked

date      5/1/2017  5/2/2017
city
mumbai        81.5      55.5
new york      55.0      61.0

In [28]:
df=pd.DataFrame(
    {
    "City": ["Delhi", "Delhi", "Mumbai", "Delhi", "Mumbai"],
    "Weather": ["Sunny", "Rainy", "Sunny", "Sunny", "Rainy"]
     })
df

     City Weather
0   Delhi   Sunny
1   Delhi   Rainy
2  Mumbai   Sunny
3   Delhi   Sunny
4  Mumbai   Rainy

In [29]:
ct = pd.crosstab(df["City"], df["Weather"])
ct

Weather  Rainy  Sunny
City
Delhi        1      2
Mumbai       1      1

In [30]:
import numpy as np

In [31]:
percent = ct.div(ct.sum(axis=1), axis=0) * 100
percent

Weather      Rainy      Sunny
City
Delhi    33.333333  66.666667
Mumbai   50.000000  50.000000

In [32]:
jan = pd.DataFrame({
    "ProductID": [1, 2, 1],
    "Sales": [200, 150, 100]
})

feb = pd.DataFrame({
    "ProductID": [1, 2, 2],
    "Sales": [250, 100, 200]
})

In [33]:
jan

   ProductID  Sales
0          1    200
1          2    150
2          1    100

In [34]:
feb

   ProductID  Sales
0          1    250
1          2    100
2          2    200

In [35]:
all_sales = pd.concat([jan, feb], keys=["Jan", "Feb"], names=["Month"])
all_sales = all_sales.reset_index(level=0)
all_sales

  Month  ProductID  Sales
0   Jan          1    200
1   Jan          2    150
2   Jan          1    100
0   Feb          1    250
1   Feb          2    100
2   Feb          2    200

In [36]:
products = pd.DataFrame({
    "ProductID": [1, 2],
    "ProductName": ["Laptop", "Phone"]
})

merged = all_sales.merge(products, on="ProductID")
merged

  Month  ProductID  Sales ProductName
0   Jan          1    200      Laptop
1   Jan          2    150       Phone
2   Jan          1    100      Laptop
3   Feb          1    250      Laptop
4   Feb          2    100       Phone
5   Feb          2    200       Phone

In [37]:
products.to_csv("product.csv")

In [38]:
pivot = pd.pivot_table(
    merged,
    index="ProductName",
    columns="Month",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)
pivot

Month        Feb  Jan
ProductName
Laptop       250  300
Phone        300  150

In [39]:
ct = pd.crosstab(merged["ProductName"], merged["Month"])
ct

Month        Feb  Jan
ProductName
Laptop         1    2
Phone          2    1

In [40]:
percentage = pivot.div(pivot.sum().sum()) * 100
percentage

Month         Feb   Jan
ProductName
Laptop       25.0  30.0
Phone        30.0  15.0

## Assignment

In [41]:
df1 = pd.DataFrame({
    "ProductID": [101, 102, 103, 101],
    "Region": ["North", "South", "East", "West"],
    "Sales": [12000, 15000, 10000, 9000]
})

df1

   ProductID Region  Sales
0        101  North  12000
1        102  South  15000
2        103   East  10000
3        101   West   9000

In [42]:
df2 = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "Region": ["North", "South", "East", "West"],
    "Sales": [14000, 16000, 11000, 13000]
})

df2

   ProductID Region  Sales
0        101  North  14000
1        102  South  16000
2        103   East  11000
3        104   West  13000

In [43]:
df3 = pd.DataFrame({
    "ProductID": [101, 102, 104, 103],
    "Region": ["North", "South", "East", "West"],
    "Sales": [15500, 17000, 12500, 9500]
})

df3

   ProductID Region  Sales
0        101  North  15500
1        102  South  17000
2        104   East  12500
3        103   West   9500

In [44]:
df=pd.concat([df1,df2,df3])
df

   ProductID Region  Sales
0        101  North  12000
1        102  South  15000
2        103   East  10000
3        101   West   9000
0        101  North  14000
1        102  South  16000
2        103   East  11000
3        104   West  13000
0        101  North  15500
1        102  South  17000
2        104   East  12500
3        103   West   9500

In [45]:
price_df = pd.DataFrame({
    "ProductID": [101, 102, 103, 104],
    "Price": [50, 40, 30, 60]
})

price_df

   ProductID  Price
0        101     50
1        102     40
2        103     30
3        104     60

In [46]:
merged_df = df.merge(price_df, on="ProductID", how="inner")
merged_df

    ProductID Region  Sales  Price
0         101  North  12000     50
1         102  South  15000     40
2         103   East  10000     30
3         101   West   9000     50
4         101  North  14000     50
5         102  South  16000     40
6         103   East  11000     30
7         104   West  13000     60
8         101  North  15500     50
9         102  South  17000     40
10        104   East  12500     60
11        103   West   9500     30

In [47]:
merged_df["Revenue"] = np.multiply(
    merged_df["Sales"].values,
    merged_df["Price"].values
)

merged_df

    ProductID Region  Sales  Price  Revenue
0         101  North  12000     50   600000
1         102  South  15000     40   600000
2         103   East  10000     30   300000
3         101   West   9000     50   450000
4         101  North  14000     50   700000
5         102  South  16000     40   640000
6         103   East  11000     30   330000
7         104   West  13000     60   780000
8         101  North  15500     50   775000
9         102  South  17000     40   680000
10        104   East  12500     60   750000
11        103   West   9500     30   285000

In [48]:
revenue_per_product = merged_df.groupby("ProductID")["Revenue"].sum()

revenue_per_product

ProductID
101    2525000
102    1920000
103     915000
104    1530000
Name: Revenue, dtype: int64

In [49]:
data=pd.DataFrame({
    "City": ["Delhi", "Delhi", "Mumbai", "Mumbai", "Chennai"],
    "Month": ["Jan", "Feb", "Jan", "Feb", "Jan"],
    "Sales": [20000, 22000, 18000, 21000, 15000]
})

In [50]:
data

      City Month  Sales
0    Delhi   Jan  20000
1    Delhi   Feb  22000
2   Mumbai   Jan  18000
3   Mumbai   Feb  21000
4  Chennai   Jan  15000

In [51]:
pivot_total = pd.pivot_table(
    data,
    index="City",
    columns="Month",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)

pivot_total

Month      Feb    Jan
City
Chennai      0  15000
Delhi    22000  20000
Mumbai   21000  18000

In [52]:
pivot_avg = pd.pivot_table(
    data,
    index="City",
    columns="Month",
    values="Sales",
    aggfunc="mean",
    fill_value=0
)

pivot_avg

Month        Feb      Jan
City
Chennai      0.0  15000.0
Delhi    22000.0  20000.0
Mumbai   21000.0  18000.0

In [53]:
marks_df = pd.DataFrame({
    "Student": ["Amit", "Riya", "Karan"],
    "Maths": [85, 90, 78],
    "Science": [88, 92, 80],
    "English": [75, 85, 82]
})

marks_df

  Student  Maths  Science  English
0    Amit     85       88       75
1    Riya     90       92       85
2   Karan     78       80       82

In [54]:
long_marks = marks_df.melt(
    id_vars="Student",
    value_vars=["Maths", "Science", "English"],
    var_name="Subject",
    value_name="Marks"
)

long_marks

  Student  Subject  Marks
0    Amit    Maths     85
1    Riya    Maths     90
2   Karan    Maths     78
3    Amit  Science     88
4    Riya  Science     92
5   Karan  Science     80
6    Amit  English     75
7    Riya  English     85
8   Karan  English     82

In [55]:
survey = pd.DataFrame({
    "Department": ["CS", "CS", "IT", "IT", "CS", "ECE"],
    "Grade": ["A", "B", "A", "B", "A", "A"]
})

survey

  Department Grade
0         CS     A
1         CS     B
2         IT     A
3         IT     B
4         CS     A
5        ECE     A

In [56]:
ct = pd.crosstab(survey["Department"], survey["Grade"])
ct

Grade       A  B
Department
CS          2  1
ECE         1  0
IT          1  1

In [57]:
percentage_ct = np.round(
    (ct / ct.sum(axis=1).values.reshape(-1, 1)) * 100,
    2
)

percentage_ct

Grade            A      B
Department
CS           66.67  33.33
ECE         100.00   0.00
IT           50.00  50.00